[package]
name = "speck"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[build-dependencies]
swift-bridge-build = "0.1"

[lib]
crate-type = ["staticlib"]

[dependencies]
swift-bridge = {version = "0.1", features = ["async"]}
librespot = "0.4.2"
env_logger = "0.10.0"
log = "0.4.17"