// File automatically generated by swift-bridge.
typedef struct Speck Speck;
void __swift_bridge__$Speck$_free(void* self);

void* __swift_bridge__$Vec_Speck$new(void);
void __swift_bridge__$Vec_Speck$drop(void* vec_ptr);
void __swift_bridge__$Vec_Speck$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_Speck$pop(void* vec_ptr);
void* __swift_bridge__$Vec_Speck$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_Speck$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_Speck$len(void* vec_ptr);
void* __swift_bridge__$Vec_Speck$as_ptr(void* vec_ptr);

void* __swift_bridge__$Speck$new(void);
void __swift_bridge__$Speck$init(void* callback_wrapper, void __swift_bridge__$Speck$init$async(void* callback_wrapper, struct __private__ResultPtrAndPtr ret), void* self, struct RustStr username, struct RustStr password);


