name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-15
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: rustup toolchain install
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Cargo build
        run: cargo build --release
      - name: Build
        run: |
           xcodebuild clean build analyze -scheme Speck -project Speck/Speck.xcodeproj | xcpretty && exit ${PIPESTATUS[0]}
